# Generated by Django 5.1.6 on 2025-03-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpearJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('params', models.TextField()),
                ('priority', models.IntegerField(default=5)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('result', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('celery_job_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
