# Generated by Django 5.1.6 on 2025-11-11 08:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RayStationSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system_name", models.CharField(max_length=100, unique=True)),
                ("system_uid", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SpearJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("logs", models.TextField(blank=True, null=True)),
                ("celery_job_id", models.CharField(max_length=100, unique=True)),
                (
                    "worker_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "server_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HPTC-RAY-SP01", "HPTC-RAY-SP01"),
                            ("HPTC-RAY-SP02", "HPTC-RAY-SP02"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "workflow_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("workflow_config", models.JSONField(blank=True, null=True)),
                ("latest_heartbeat", models.DateTimeField(blank=True, null=True)),
                (
                    "priority",
                    models.SmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MaxValueValidator(1),
                            django.core.validators.MinValueValidator(10),
                        ],
                    ),
                ),
                (
                    "raystation_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spear_jobs",
                        to="spear_job_api.raystationsystem",
                    ),
                ),
            ],
        ),
    ]
