# Generated by Django 5.1.6 on 2025-11-12 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spear_job_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="raystationsystem",
            options={
                "verbose_name": "RayStation System",
                "verbose_name_plural": "RayStation Systems",
            },
        ),
        migrations.AlterField(
            model_name="spearjob",
            name="priority",
            field=models.SmallIntegerField(
                default=5,
                validators=[
                    django.core.validators.MaxValueValidator(10),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
