# Generated by Django 5.1.6 on 2025-03-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spear_job_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spearjob',
            name='server_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spearjob',
            name='worker_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
