# Generated by Django 5.1.6 on 2025-03-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spear_job_api', '0002_spearjob_server_name_spearjob_worker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='spearjob',
            name='args',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spearjob',
            name='kwargs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
