# Generated by Django 5.1.6 on 2025-11-12 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spear_job_api", "0002_alter_raystationsystem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spearjob",
            name="celery_job_id",
            field=models.CharField(
                help_text="UUID-like job ID (lowercase hex + dashes)",
                max_length=36,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="celery_job_id must contain only lowercase hex digits and hyphens.",
                        regex="^[0-9a-f-]+$",
                    )
                ],
            ),
        ),
    ]
