# Generated by Django 5.1.6 on 2025-03-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spear_job_api', '0004_remove_spearjob_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spearjob',
            name='server_name',
            field=models.CharField(blank=True, choices=[('A', 'SPEAR Server A'), ('B', 'SPEAR Server B')], max_length=100, null=True),
        ),
    ]
