# Generated by Django 5.1.6 on 2025-03-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spear_job_api', '0005_alter_spearjob_server_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spearjob',
            name='celery_job_id',
            field=models.CharField(default='test', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
