version: "3.12"


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=true
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    command: >
        sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    environment:
      - DB_HOST=postgres
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/C/Program Files/PostgreSQL/15/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

  rabbitmq:
    image: rabbitmq:3.9.7-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management UI

  celery:
    container_name: celery
    build:
      context: .
      args:
        - DEV=true
    volumes:
      - ./app:/app
    environment:
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - app
      - rabbitmq

  celery-worker1:
    # TODO: create another folder for worker, instead of using the one in django
    container_name: celery-worker1
    build:
      context: .
      args:
        - DEV=true
    command: >
      celery -A app worker --hostname=worker-spear-serverA@%h --loglevel=info --concurrency=1 -E
    volumes:
      - ./app:/app
    environment:
      - ALLOWED_HOSTS=localhost,
      - QUEUE_API_HOST=app
      - QUEUE_API_PORT=8080


  celery-worker2:
    container_name: celery-worker2
    build:
      context: .
      args:
        - DEV=true
    command: >
      celery -A app worker --hostname=worker-spear-serverB@%h --loglevel=info --concurrency=1 -E
    volumes:
      - ./app:/app
    environment:
      - ALLOWED_HOSTS=localhost,
      - QUEUE_API_HOST=app
      - QUEUE_API_PORT=8080

  flower:
    image: mher/flower
    container_name: flower
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - rabbitmq

  redis:
    image: redis:7.0.11-alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  dev-db-data: